print("Welcome to the Band Name Generator.")
city = input("What's the name of the city you grew up in?")
print(city)
pet = input("What is your pet's name?")
print(pet)
print("Your band name could be " +city+ " " + pet)